null check to fix:
java.lang.NullPointerException: Cannot invoke
"org.sablo.IWebObjectContext.getUnderlyingWebObject()" because
"this.parentWebObjectContext" is null
at org.sablo.CustomObjectContext.getUnderlyingWebObject(CustomObjectContext.java:105)
~[sablo_2024.12.0.4020_rc.jar:?]
at com.servoy.j2db.server.ngclient.property.types.FormPropertyType.toRhinoValue(FormPropertyType.java:205)
~[servoy_ngclient_2024.12.0.4020_rc.jar:?]
at com.servoy.j2db.server.ngclient.property.types.NGConversions.convertSabloComponentToRhinoValue(NGConversions.java:489)
~[servoy_ngclient_2024.12.0.4020_rc.jar:?]
at com.servoy.j2db.server.ngclient.component.RhinoMapOrArrayWrapper.get(RhinoMapOrArrayWrapper.java:156)
~[servoy_ngclient_2024.12.0.4020_rc.jar:?]
at com.servoy.j2db.util.Utils.getScriptableString(Utils.java:3517)
~[servoy_shared_2024.12.0.4020_rc.jar:?]
at com.servoy.j2db.util.Utils.getScriptableString(Utils.java:3424)
~[servoy_shared_2024.12.0.4020_rc.jar:?]
at com.servoy.j2db.server.ngclient.component.EventExecutor.lambda$0(EventExecutor.java:241)
~[servoy_ngclient_2024.12.0.4020_rc.jar:?]